import { AppWindow, Boxes, CloudCog, Database, HardDrive, Network, Server, ShieldCheck, Users, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import PageHero from '@/components/PageHero';
import SectionHeading from '@/components/SectionHeading';
import Reveal from '@/components/Reveal';
import FinalCTA from '@/components/FinalCTA';

const SERVICES = [{ icon: Server, title: 'Dedicated Server Solutions', desc: 'Bare-metal infrastructure for workloads that need dedicated performance and control.' }, { icon: Boxes, title: 'Virtual Machines', desc: 'Flexible, isolated compute environments for business and technical workloads.' }, { icon: CloudCog, title: 'DevOps Solutions', desc: 'Infrastructure support for deployment, automation and dependable delivery.' }, { icon: Network, title: 'Cloud Infrastructure Management', desc: 'Practical management across compute, storage, networking and access.' }, { icon: Users, title: 'Managed IT Services', desc: 'Human support and ongoing operational guidance for your infrastructure.' }];
const FLOW = [{ icon: Network, label: 'Network' }, { icon: Server, label: 'Compute' }, { icon: HardDrive, label: 'Storage' }, { icon: Boxes, label: 'Virtualization' }, { icon: AppWindow, label: 'Applications' }, { icon: Database, label: 'Backup' }];
const USE_CASES = ['Business Applications', 'Enterprise Workloads', 'Development', 'Hosting', 'Remote Work', 'Custom Infrastructure'];

export default function InfrastructurePage() {
  return <>
    <PageHero eyebrow="Infrastructure & Managed IT" title="Build Infrastructure Around Your Business." description="Design and operate the infrastructure your business needs across compute, storage, virtualization, applications and backup."><Link to="/contact" className="btn-blue mt-8">Build Custom Infrastructure <ArrowRight className="h-4 w-4" /></Link></PageHero>
    <section className="section-pad bg-white"><div className="container-base"><SectionHeading eyebrow="Infrastructure Stack" title="A connected foundation for critical work" description="See how the core layers come together to support the applications and teams that keep your business moving." /><Reveal className="mt-14"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{FLOW.map((node, i) => <div key={node.label} className="relative"><div className="flex h-full flex-col items-center rounded-2xl border border-navy-100 bg-white p-5 text-center shadow-sm"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-navy-900 text-blue-400"><node.icon className="h-6 w-6" /></span><span className="mt-4 text-sm font-bold text-navy-900">{node.label}</span></div>{i < FLOW.length - 1 && <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden h-5 w-5 -translate-y-1/2 text-navy-300 lg:block" />}</div>)}</div></Reveal></div></section>
    <section className="section-pad bg-navy-50/40"><div className="container-base"><SectionHeading eyebrow="What We Deliver" title="Infrastructure services with a business view" description="Choose the layer of support that matches your operating model, from dedicated infrastructure to managed IT." /><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{SERVICES.map((service, i) => <Reveal key={service.title} delay={i * 70}><div className="h-full rounded-2xl border border-navy-100 bg-white p-6 transition-all hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-navy-900 text-blue-400"><service.icon className="h-6 w-6" /></span><h3 className="mt-5 text-lg font-bold text-navy-900">{service.title}</h3><p className="mt-2 text-sm leading-relaxed text-navy-600">{service.desc}</p></div></Reveal>)}</div></div></section>
    <section className="section-pad bg-white"><div className="container-base"><div className="grid items-center gap-10 lg:grid-cols-2"><Reveal><h2 className="text-3xl font-bold text-navy-900 sm:text-4xl">Built for the way your business works</h2><p className="mt-5 text-navy-600">Infrastructure is most useful when it is shaped around the work it needs to support. Start with a clear workload, then build the right foundation around it.</p></Reveal><Reveal delay={100}><div className="grid grid-cols-2 gap-3">{USE_CASES.map(item => <div key={item} className="rounded-xl border border-navy-100 bg-navy-50/50 p-4 text-sm font-semibold text-navy-800">{item}</div>)}</div></Reveal></div></div></section>
    <section className="section-pad bg-white pt-0"><div className="container-base"><FinalCTA /></div></section>
  </>;
}
